### ISSUE TITLE
Better Spacing of Themes

### ISSUE THREAD

**Issue by TerabyteTiger** [12vanblart/color-themes#27]
It would be nice if the themes would center under the "Choose a new theme" banner. 

I *think* this can be achieved in an accessible manner by wrapping the buttons in a div and using `marign: auto`

**Comment by TerabyteTiger** [comment]
@stroudn1 - Want to take a look at this?

**Comment by natastro** [comment]
@12vanblart Definitely :)

**Comment by natastro** [comment]
I'm a super newbie but it looks like maybe my PR got referenced in this issue? Let me know if you've got any feedback :D

**Comment by TerabyteTiger** [comment]
This was fixed with #33
