### ISSUE TITLE
Add a "Copy Colors" button to Popper

### ISSUE THREAD

**Issue by TerabyteTiger** [12vanblart/color-themes#3]
Add a button to the bottom of the Popper popout to copy theme to clipboard. 

I.e. Clicking this button while the default-light theme is selected would copy 

```
.default-light {
  --primary: #351c4d;
  --secondary: #fff;
  --accent: #f5ab99;
  --link: #674672;
  --text: #351c4d;
}
```

**Comment by mblancodev** [comment]
I would like to take this

**Comment by TerabyteTiger** [comment]
Functionality added by #28
